CU-868abtuk1_update-synced-property-for-multiple-remotes-sync
neutrinographics/event_sink pull request #11
Opened 2024-10-29 08:35 UTC by dhemasnurjaya

2024-10-29 08:35 UTC, da1nerd commented
Task linked: [CU-868abtuk1 update synced property for multiple remotes sync](https://app.clickup.com/t/868abtuk1)

2024-10-29 09:26 UTC, da1nerd commented on lib/src/feature/data/repositories/event_repository_impl.dart
>                order: e.order,
should prioritize the order of the highest priority adapter.

Example: if the event was synced with a lower priority adapter, but has already been synced with a higher priority adapter, the original order should be preserved.

2024-10-29 09:28 UTC, da1nerd commented on lib/src/feature/data/repositories/event_repository_impl.dart
>              remoteEvent: syncedEvent.first,
This is skipping the rest of the event in the list.

2024-10-29 09:30 UTC, da1nerd commented on lib/src/feature/data/repositories/event_repository_impl.dart
>            ).copyWith(applied: e.applied, createdAt: timeInfo.now()),
These events might have already been synced to another adapter, so we need to preserve the sync status of those adapter, and also the order of the highest priority adapter.

2024-10-30 07:16 UTC, dhemasnurjaya commented on lib/src/feature/data/repositories/event_repository_impl.dart
>              remoteEvent: syncedEvent.first,
It is not, this code is inside a for loop for each event. But it will better to do a batch push since the method can take a list of events as arg

2024-10-30 07:40 UTC, dhemasnurjaya commented on lib/src/feature/data/repositories/event_repository_impl.dart
>                order: e.order,
this will be a problem with our current approach because adapter priority only exists in the app (LKKK), need more discussion for this

2024-10-30 07:41 UTC, dhemasnurjaya commented on lib/src/feature/data/repositories/event_repository_impl.dart
>            ).copyWith(applied: e.applied, createdAt: timeInfo.now()),
same as previous comment regarding adapter priority

2024-11-01 09:11 UTC, da1nerd requested changes
Looking good! But here are some suggestions 😄

2024-11-01 09:11 UTC, da1nerd commented on test/core/data/event_resolver_impl_test.dart
Add another test for when the local event and adapter event adapters both have the same priority.
In that case let's return the adapter event.

2024-11-01 09:11 UTC, da1nerd commented on lib/src/core/data/event_resolver.dart
> +    final existingEventPriority = newEventRemoteAdapter.priority;
Instead of adding inline documentation like this, it is preferable to split the code into functions, or let the tests document the code.

Splitting the code into functions is mostly useful to help with readability. And the tests are helpful in documenting the expected outcome of the code.

The problem with inline documentation like this is it's often never maintained, and can become out of date.

2024-11-01 11:55 UTC, dhemasnurjaya commented on test/core/data/event_resolver_impl_test.dart
code updated!

2024-11-01 11:55 UTC, dhemasnurjaya commented on lib/src/core/data/event_resolver.dart
> +    final existingEventPriority = newEventRemoteAdapter.priority;
done!

2024-11-04 04:17 UTC, Var-J approved these changes
LGTM

2024-11-04 07:19 UTC, da1nerd approved these changes

2024-11-04 07:19 UTC, merged