preserve synced field in EventModel.fromRemote
neutrinographics/event_sink pull request #20
Opened 2024-12-12 09:59 UTC by dhemasnurjaya

2024-12-12 09:59 UTC, da1nerd commented
Task linked: [CU-868b8nhcq Update .fromRemote in event_sink to preserve sync field](https://app.clickup.com/t/868b8nhcq)

2024-12-13 06:13 UTC, da1nerd requested changes

2024-12-13 06:13 UTC, da1nerd commented on lib/src/feature/data/local/models/event_model.dart
> +      synced: Map.from(synced)..addAll({remoteAdapterName: true}),
This feels strange. We may has well add the adapter name to `synced` before passing it to this method. Then we can avoid passing in the `remoteAdapterName`.

2024-12-13 06:13 UTC, da1nerd commented on lib/src/feature/data/repositories/event_repository_impl.dart
> +    List<EventModel> pooledEvents;
This does not need to be declared separate from it's initialization since it's not used outside of the try block.

2024-12-13 06:13 UTC, da1nerd commented on test/feature/data/repositories/event_repository_impl_test.dart
Should test that an existing entry in the event's synced property will be preserved when syncing to another adapter.

2024-12-13 10:11 UTC, dhemasnurjaya commented on lib/src/feature/data/local/models/event_model.dart
> +      synced: Map.from(synced)..addAll({remoteAdapterName: true}),
Actually, for now a `synced` entry only added after an event is fetched from a remote. So the `synced` property will never has `{remoteAdapterName: false}` entry. I think it's better to change `synced` property to `List<String>` instead of a `Map`

2024-12-13 10:20 UTC, dhemasnurjaya commented on lib/src/feature/data/repositories/event_repository_impl.dart
> +    List<EventModel> pooledEvents;
It is needed to access `synced` property from cached `EventModel`, since `RemoteEventModel` doesn't have any information about it

2024-12-16 02:06 UTC, da1nerd commented on lib/src/feature/data/local/models/event_model.dart
> +      synced: Map.from(synced)..addAll({remoteAdapterName: true}),
That's a great idea. Please do that.

2024-12-16 04:32 UTC, dhemasnurjaya commented on lib/src/feature/data/local/models/event_model.dart
> +      synced: Map.from(synced)..addAll({remoteAdapterName: true}),
done

2024-12-16 10:01 UTC, da1nerd approved these changes

2024-12-16 10:01 UTC, merged